M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-12-26T22:23:56+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-26T22:23:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X127.117Y-90.734
X138.547Y-90.734
M30
